[package]
name = "Examples"
version = "0.0.0"

[addresses]
MyModule = "0x8f5c597b7f63c05b067441d29fa47c7d74ce4aa9f968f3c8f071f6d4e743aae0"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "aptos-node-v1.2.0" }